name: Hello_world workflows

on:
  push:
   branches:
     -main
  pull_requests:
   branches:
     -main:
  workflows_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: hello world
        run: echo "Hello world"
        shell: bash

   goodbye:
    runs-on: ubuntu-latest
    steps:
        -name: goodbye world
        run: echo "goodbye world"